name: Broken Links Checker

on:
  push:
    branches:
      - main
  schedule:
    - cron: "00 18 * * *"
  workflow_dispatch: 

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: .
          fail: false

      - name: Create lychee report
        if: always()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Broken Links Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
